
// Post Actions
export const CREATE_POST = "CREATE_POST"
export const DELETE_POST = "DELETE_POST"
export const LOADING_POSTS = "LOADING_POSTS"
export const FETCH_POSTS = "FETCH_POSTS"
export const EDIT_POST = "EDIT_POST"
export const UPDATE_POST = "UPDATE_POST"

// Auth Action
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT = "LOGOUT"